-- MySQL Script generated by MySQL Workbench
-- 08/29/16 18:55:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nutriologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nutriologo` (
  `idNutriologo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `apellidoPat` VARCHAR(45) NULL,
  `apellidoMat` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  `admin_idadmin` INT NULL,
  `tel` INT NULL,
  PRIMARY KEY (`idNutriologo`),
  INDEX `fk_Nutriologo_admin1_idx` (`admin_idadmin` ASC),
  CONSTRAINT `fk_Nutriologo_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `mydb`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dietas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dietas` (
  `idDietas` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Nutriologo_idNutriologo` INT NOT NULL,
  `descripcion` VARCHAR(1000) NULL,
  PRIMARY KEY (`idDietas`),
  INDEX `fk_Dietas_Nutriologo1_idx` (`Nutriologo_idNutriologo` ASC),
  CONSTRAINT `fk_Dietas_Nutriologo1`
    FOREIGN KEY (`Nutriologo_idNutriologo`)
    REFERENCES `mydb`.`Nutriologo` (`idNutriologo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DietasValoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DietasValoracion` (
  `valoracion` INT NOT NULL,
  `Dietas_idDietas` INT NOT NULL,
  `fecha` DATETIME NULL,
  `idDietasValoracion` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idDietasValoracion`),
  INDEX `fk_DietasValoracion_Dietas1_idx` (`Dietas_idDietas` ASC),
  CONSTRAINT `fk_DietasValoracion_Dietas1`
    FOREIGN KEY (`Dietas_idDietas`)
    REFERENCES `mydb`.`Dietas` (`idDietas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alimento` (
  `idAlimento` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `available` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idAlimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dietas_has_Alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dietas_has_Alimento` (
  `Dietas_idDietas` INT NOT NULL,
  `Alimento_idAlimento` INT NOT NULL,
  `cantidad` FLOAT NULL,
  `unidad` VARCHAR(45) NULL,
  PRIMARY KEY (`Dietas_idDietas`, `Alimento_idAlimento`),
  INDEX `fk_Dietas_has_Alimento_Alimento1_idx` (`Alimento_idAlimento` ASC),
  INDEX `fk_Dietas_has_Alimento_Dietas1_idx` (`Dietas_idDietas` ASC),
  CONSTRAINT `fk_Dietas_has_Alimento_Dietas1`
    FOREIGN KEY (`Dietas_idDietas`)
    REFERENCES `mydb`.`Dietas` (`idDietas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dietas_has_Alimento_Alimento1`
    FOREIGN KEY (`Alimento_idAlimento`)
    REFERENCES `mydb`.`Alimento` (`idAlimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


ALTER TABLE admin AUTO_INCREMENT=1001;
ALTER TABLE nutriologo AUTO_INCREMENT=1;
ALTER TABLE dietas AUTO_INCREMENT=1;
ALTER TABLE dietasValoracion AUTO_INCREMENT=1;
ALTER TABLE alimento AUTO_INCREMENT=1;
