-- MySQL Script generated by MySQL Workbench
-- 08/19/16 19:05:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dietas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dietas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dietas` DEFAULT CHARACTER SET utf8 ;
USE `dietas` ;

-- -----------------------------------------------------
-- Table `dietas`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietas`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietas`.`Nutriologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietas`.`Nutriologo` (
  `idNutriologo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `apellidoPat` VARCHAR(45) NULL,
  `apellidoMat` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  `admin_idadmin` INT NULL,
  `tel` INT NULL,
  PRIMARY KEY (`idNutriologo`),
  INDEX `fk_Nutriologo_admin1_idx` (`admin_idadmin` ASC),
  CONSTRAINT `fk_Nutriologo_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `dietas`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietas`.`Dietas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietas`.`Dietas` (
  `idDietas` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Nutriologo_idNutriologo` INT NOT NULL,
  `descripcion` VARCHAR(1000) NULL,
  PRIMARY KEY (`idDietas`),
  INDEX `fk_Dietas_Nutriologo1_idx` (`Nutriologo_idNutriologo` ASC),
  CONSTRAINT `fk_Dietas_Nutriologo1`
    FOREIGN KEY (`Nutriologo_idNutriologo`)
    REFERENCES `dietas`.`Nutriologo` (`idNutriologo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietas`.`DietasValoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietas`.`DietasValoracion` (
  `valoracion` INT NOT NULL,
  `Dietas_idDietas` INT NOT NULL,
  `fecha` DATETIME NULL,
  `idDietasValoracion` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idDietasValoracion`),
  INDEX `fk_DietasValoracion_Dietas1_idx` (`Dietas_idDietas` ASC),
  CONSTRAINT `fk_DietasValoracion_Dietas1`
    FOREIGN KEY (`Dietas_idDietas`)
    REFERENCES `dietas`.`Dietas` (`idDietas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietas`.`Alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietas`.`Alimento` (
  `idAlimento` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idAlimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietas`.`Dietas_has_Alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietas`.`Dietas_has_Alimento` (
  `Dietas_idDietas` INT NOT NULL,
  `Alimento_idAlimento` INT NOT NULL,
  `cantidad` FLOAT NULL,
  `unidad` VARCHAR(45) NULL,
  PRIMARY KEY (`Dietas_idDietas`, `Alimento_idAlimento`),
  INDEX `fk_Dietas_has_Alimento_Alimento1_idx` (`Alimento_idAlimento` ASC),
  INDEX `fk_Dietas_has_Alimento_Dietas1_idx` (`Dietas_idDietas` ASC),
  CONSTRAINT `fk_Dietas_has_Alimento_Dietas1`
    FOREIGN KEY (`Dietas_idDietas`)
    REFERENCES `dietas`.`Dietas` (`idDietas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dietas_has_Alimento_Alimento1`
    FOREIGN KEY (`Alimento_idAlimento`)
    REFERENCES `dietas`.`Alimento` (`idAlimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE admin AUTO_INCREMENT=1001;
ALTER TABLE nutriologo AUTO_INCREMENT=1;
ALTER TABLE dietas AUTO_INCREMENT=1;
ALTER TABLE dietasValoracion AUTO_INCREMENT=1;
ALTER TABLE alimento AUTO_INCREMENT=1;